import { useEffect, useMemo, useState } from "react";
import ProductCard from "./Components/ProductCard";

export default function HomePage() {
  const [products, setProducts] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [search, setSearch] = useState("");
  useEffect(() => { const controller = new AbortController(); async function loadProducts() { try { const response = await fetch("https://fakestoreapi.com/products?limit=6", { signal: controller.signal }); if (!response.ok) throw new Error(); setProducts(await response.json()); } catch (requestError) { if (requestError.name !== "AbortError") setError("Failed to load products. Please try again later."); } finally { if (!controller.signal.aborted) setLoading(false); } } loadProducts(); return () => controller.abort(); }, []);
  const filteredProducts = useMemo(() => products.filter((product) => product.title.toLowerCase().includes(search.toLowerCase())), [products, search]);
  return <><section className="catalog-hero" aria-labelledby="catalog-title"><div className="content-wrap hero-content"><p className="eyebrow">CCS-112 React Store</p><h1 id="catalog-title">Everyday tech, clearly presented.</h1><p>Browse a small catalog powered by live data, reusable components, and React state.</p></div></section><section className="catalog-section content-wrap" aria-labelledby="products-title"><div className="section-heading"><div><p className="eyebrow">Product catalog</p><h2 id="products-title">Find your next essential</h2></div><label className="search-box"><span className="sr-only">Search products</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search products" /></label></div>{loading && <p className="status-message">Loading products...</p>}{error && <p className="status-message status-error">{error}</p>}{!loading && !error && <div className="product-grid">{filteredProducts.length ? filteredProducts.map((product) => <ProductCard key={product.id} product={product} />) : <p className="status-message">No products match your search.</p>}</div>}</section></>;
}
